### ISSUE TITLE
[Linux/MacOS] Right click not working

### ISSUE THREAD

**Issue by Robbendebiene** [Robbendebiene/Gesturefy#1]
Currently there is a different context menu behavior for Linux and MacOS which breaks the entire gesture functionality.
See this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1360278

**Comment by MurzNN** [comment]
As workaround we can stay FireGestures plugin active (with disabled gesture) that disable instant menu showing, and use it together with new Gesturefy :)

**Comment by TamasBarta** [comment]
Firefox Developer Edition 58.0b1 is out, are the platform limitations fixed in that version?

**Comment by frinnst** [comment]
Foxygestures (https://github.com/marklieberman/foxygestures) seems to have worked around this issue somewhat. The context menu still appears but gestures work.

**Comment by fengchang** [comment]
I am so disappointed that Mozilla release a browser doesn't support mouse gesture.

**Comment by JamesMackerel** [comment]
I am currently using a Chrome on Linux, which is also not able to develop a perfect mouse gesture plugin like Windows. But it solved the question in a different way. When the right button clicked, the quick menu would not shown and everything works fine like a perfect mouse gesture plugin, but neither will the quick menu shown when you just press a right click. The right menu will be shown when you DOUBLE-CLICK the right button.

I hope this will help, in some degree. However, thank you for developing this plugin. :)

**Comment by stmr** [comment]
@frinnst @Robbendebiene this looks like the commit that made the double click thing, but it's a workaround. https://github.com/marklieberman/foxygestures/pull/109/commits/722cb7262201bc16c3ff4835c1194fa43e5c89c6
There are however patched versions for both linux and macOs that have option to open context menu the same way as on windows so it will work soon (let's hope).

**Comment by frinnst** [comment]
@stmr Do you have a copy of or commit for that patch? I build firefox from source so it would be nice to test it

**Comment by stmr** [comment]
@frinnst Hi, you can find it in attachments on bugzilla (link in first post of this page). It's been merged to factory/tumbleweed in OpenSuse and I can confirm it working flawlessly with Gesturefy. Let's hope it will be fixed soon in upstream.

**Comment by alexivkin** [comment]
Pushed to the main trunk for v 59 "ui.context_menus.after_mouseup"

**Comment by jerryjune** [comment]
https://addons.mozilla.org/zh-CN/firefox/addon/mouse-gestures/
https://addons.mozilla.org/zh-CN/firefox/addon/basic-gestures/
these two basic mouse gestures can use right button on FF57, they will use double click to open context menu. Even on chrome platform, crxMouse also use double click to open context menu. 
Again, this is platform difference, is not firefox bug

**Comment by Robbendebiene** [comment]
@jerryjune technically not, but it can be considered as one (at least from a user perspective view). At the end it's more a lack of api, because it was possible before to change this behaviour.

**Comment by TamasBarta** [comment]
@alexivkin can you reference the actual commit? Thanks!

**Comment by stmr** [comment]
Resolved FIXED for version 59 🤣

**Comment by nazar-pc** [comment]
Yeah, waiting for new Nightly build to test it 🎆

**Comment by GSF1200S** [comment]
Arch Linux has backported this fix for Firefox 57... it will show up as firefox-57.0-2 and has already hit my mirror. There is still a single kink for Rocker Gestures, but I'm not sure it can be fixed given the limitation of webextensions on about:newtab etc. I started a bug here to find out: https://github.com/Robbendebiene/Gesturefy/issues/164

**Comment by eworm-de** [comment]
You may be interested in [Implement browserSettings.contextMenuShowEvent](https://hg.mozilla.org/integration/autoland/rev/d4779e0fdbbb), which exposes the setting `ui.context_menus.after_mouseup` to webextensions. Please make `gesturefy` modify the setting to make things work automatically.

**Comment by stmr** [comment]
@eworm-de see #161

**Comment by VBelozyorov** [comment]
FYI: `ui.context_menus.after_mouseup` is already available in Firefox 58 beta 6 from FF website.

**Comment by ayuanx** [comment]
So, what's the solution on MacOS?

I can't use left button otherwise I won't be able to select certain texts.
I can't use right button because it doesn't work!
I can't use middle button because there is no middle button on a Macbook trackpad.

**Comment by VBelozyorov** [comment]
@ayuanx you may install v58beta, it's quite stable, I suppose. 
Then open `about:config` and set `ui.context_menus.after_mouseup` to `true`, after that gestures with right button should start working.

**Comment by ayuanx** [comment]
OK. I will give v58beta a try.

**Comment by frinnst** [comment]
I can confirm that it works for me on linux with 58b. But it seems that they finally killed of alsa support (no more --enable-alsa)

**Comment by jerryjune** [comment]
amazing, it's really worked. glad to see this advanced setting in next release

**Comment by ihabunek** [comment]
This has landed in Firefox Developer Edition, and works well. Thanks a lot for your work.

**Comment by dregad** [comment]
I just installed FF 58.0b15, and I confirm the right-click gestures do work as expected now. Thanks !

**Comment by Robbendebiene** [comment]
Since Firefox 58 is officially released, I'm closing this. Thanks for the support!

**Comment by pabuisson** [comment]
@Robbendebiene sorry to bother you again with this topic 😅 I'm currently running on MacOS + FF 60a and can't get right-click gestures to work. I used to make it work some time ago (weeks ago I think), didn't use it since, and now it's gone. 

I've tried uninstalling and reinstalling the addon, and resetting the addon settings in the preferences page. I've also disabled all other addons and reopened FF with only Gesturify enabled. Left-click gesture do work, but right-click gesture don't (the context menu shows up instead).

Let me know if you need more information, or if you'd rather have me open a new issue.

**Comment by VBelozyorov** [comment]
@pabuisson if you type `about:config` in address bar and then search "ui.context", what do you see there?

**Comment by pabuisson** [comment]
@VBelozyorov here's what I get : 

<img width="504" alt="capture d ecran 2018-03-01 a 19 04 09" src="https://user-images.githubusercontent.com/769918/36861158-67ba0292-1d83-11e8-95d0-20f86e42e5dd.png">

**Comment by Robbendebiene** [comment]
@pabuisson Set it to true and everything should work fine. The question is why it's not set to true automatically :/ Can you please reinstall Gesturefy and look in the console (Ctrl + Shift + J). Maybe you can find something related to the problem.

**Comment by pabuisson** [comment]
Thanks for your help guys. Indeed, it works perfectly again when I set `ui.context_menus.after_mouseup` to `true`. 

It's really weird. Now if I reset this setting to false, then uninstall and reinstall gestureify, I see the setting correctly set to `true` by the addon. I also tried to disable and then re-enable the addon, the setting is set back to false when gesturefy is disabled, and back to true when enabled. 

It's weird because this has lasted for a long time. I managed to get gestureify to work perfectly a while ago (I believe in FF 58), then I disabled it for a while, tried it again several times since, and then it was broken. I tried to reinstall, disable/enable, reset the setting... but it didn't change a thing. Honestly I have no idea what happened.

BTW now I don't get anything unusual in the browser console during addon reinstall.

**Comment by pabuisson** [comment]
Well, I'll update this thread (maybe not the appropriate way of doing things, you maintainers tell me if I need to open a new issue or something). This issue keeps on popping really often, looks like it's appearing more often these last few weeks. I then need to manually go to about:config and set `ui.context_menus.after_mouseup` but that's not really handy.

I noticed some reviews on AMO that seem related (charles.ee 19 days ago for instance, could be the same thing).

I often disable and re-enable the addon (I disable it when I'm only using a touchpad for a long time), maybe that's the cause of this issue?   Let me know if I can be of more help.

**Comment by VBelozyorov** [comment]
When you use touchpad, does enabled gesturefy creates anything troubles? Asking because I often use gestures even with touchpad: ring finger holds RMB on touchpad and middle one draws gesture :)

Maybe try to add such line from addon-installation callback to addon-enabling callback (if one exists)?
https://github.com/Robbendebiene/Gesturefy/blob/67b20470387e7de80e38ff7cdb303a6537fde3ac/src/lib/background.js#L120

**Comment by pabuisson** [comment]
Honestly, never even tried using gesturefy with the touchpad, it doesn't seem very handy. I can try with your method though!

> Maybe try to add such line from addon-installation callback to addon-enabling callback (if one exists)?

I found the [management.onDisabled](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/management/onDisabled) and [management.onEnabled](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/management/onEnabled) events. I'll try to find a moment to retrieve the source and run some tests to understand how settings are handled when addon is enabled/disabled. And if need be, I might create a pull request.

**Comment by pabuisson** [comment]
Well apparently, judging from my tests : 

- the `onInstalled` callback is triggered when I re-enable the addon, 
- when I disable the addon, the contextMenu setting is restored to its default value,
- when I enable the addon again, the `onInstalled` callback is triggered, and therefore the contextMenu setting takes the expected value.

So it seems that there's something preventing this correct behavior to happen from time to time. I have no more clue for the moment.

**Comment by Robbendebiene** [comment]
@pabuisson Hm strange. If it happens again please look for potential causes. Maybe it happens after a Firefox update, which falsely resets the about:config settings somehow?

**Comment by ali-alsabbah** [comment]
Is this currently working of Firefox 63 on Linux? I can't get the mouse to do anything.

**Comment by ali-alsabbah** [comment]
@Robbendebiene `ui.context_menus.after_mouseup` was set to false by default. That fixed it.

I didn't have an issue with this, but the troubleshooting guide is slightly confusing because in my case, it seemed like I should looking only under the `Gesturfy is not working at all.` section because it wasn't doing anything at all before I set `ui.context_menus.after_mouseup` to `true`. Not a big deal, but could be clearer.

Thanks.
