### ISSUE TITLE
Scroll on top and bottom not work

### ISSUE THREAD

**Issue by happysurf** [Robbendebiene/Gesturefy#264]
These gestures doesn't work on pages like this:
https://bugzilla.mozilla.org/show_bug.cgi?id=1347204
If you move the scrollbar with mouse cursor or move the wheel then gestures works.

**Comment by Robbendebiene** [comment]
It seems like this problem does not occur anymore.
@happysurf can you confirm this?

Possible related Firefox bugs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1139745
https://bugzilla.mozilla.org/show_bug.cgi?id=1584035

**Comment by happysurf** [comment]
> It seems like this problem does not occur anymore.
> @happysurf can you confirm this?

Yes, the problem is fixed (now on 77beta2). 
Thanks for the info.

**Comment by Robbendebiene** [comment]
Thanks for your confirmation. In this case I'm closing this bug :)

**Comment by Robbendebiene** [comment]
Sadly the issue still exists on other pages so it's still unsolved: https://add0n.com/index.html

**Comment by happysurf** [comment]
> Sadly the issue still exists on other pages so it's still unsolved: https://add0n.com/index.html

Confirmed.

**Comment by Robbendebiene** [comment]
This should be fixed in Gesturefy version [3.0.3](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.3). The actual scroll behaviour still slightly differs from pages that do not use the `scroll-behavior: smooth;` property, but most users won't event notice this.
