### ISSUE TITLE
Gestures ceased working and options screen inoperable

### ISSUE THREAD

**Issue by mattlaw** [Robbendebiene/Gesturefy#327]
### Describe your matter in detail
Gestures stopped working with no obvious cause. Possibly following an automatic update of either the browser or the plugin. Had been working fine until recently.

The options screen is blank save for the side bar, none of the links work, including the theme selectors. The `Content` iframe contains an empty document, at least according to the debugger. I can post the DOM if need be.

### Screenshots or further assistance

![gesturefy-no-options](https://user-images.githubusercontent.com/790973/44060098-6b93e348-9f4b-11e8-9e64-6c7960834b6a.PNG)

### Your System
- Operating system: Windows 10 Version 1803
- Firefox version: 61.0.2 (64-bit)
- Gesturefy version: 2.0.2

**Comment by mattlaw** [comment]
Yes, 1.2.2 is working for me too, though my settings got lost somewhere along the way.

**Comment by Itchiii** [comment]
@mattlaw I think I know what went wrong, but please post the DOM-tree in it.

@AlexFromChaos @mattlaw 
Restarting Firefox or back to version 2.0 did not help?
However, I can not reproduce the problem and thus do not understand exactly the error. There is probably some connection between you.
Can you still remember what you did shortly before? Or do you know if Gesturefy has been updated?

**Comment by AlexFromChaos** [comment]
I did the following:
1. Created a new Firefox profile 
2. Installed the same set of addons as in my main profile (NoScript and AdBlock Plus among them BTW)
3. Installed the same UI theme (just in case)
4. After switching to the new profile, Gesturefy works properly (but for this profile only)

Seems like some incompatibility issue...  The issue persists on browser restarts. Installing 2.0.0 for the main profile also shows the same behavior (Gesturefy not working, blank screen in addon options).

One more thing - addon updates were disabled for some time and the issue appeared after manually updating from some old 1.x.x version to the recent one, 2.0.2 in my case.

**Comment by AlexFromChaos** [comment]
Actually, updating to 2.0.2 via 2.0.0 seems like fixed the issue. It appears the root cause might be in updating to 2.0.2 directly from 1.x.x.

**Comment by anatoli26** [comment]
Same problem here. I don't know to which version it was updated, but 2.0.2 is not working with the exact same symptoms as the OP.

Firefox 61.0.1 on Ubuntu 16.04, resistfingerprinting enabled

Some additional restricting settings are defined in FF.

1.2.2 is working fine.

**Comment by mattlaw** [comment]
It just so happens I have an Ubuntu 16.04 install with Firefox 61.0.1 and Gesturefy 2.0.2 that's working fine.

Downgrading to 1.2.2 on the windows machine was fine until the plugin auto-upgraded back to 2.0.2, at which point all the same symptoms returned.

> Can you still remember what you did shortly before? Or do you know if Gesturefy has been updated?

I noticed it wasn't working when I'd just opened the browser. I hadn't changed anything myself and didn't notice a notification about an automatic upgrade, but there may well have been one.

I don't have access to that machine right now, but when I get back to it I'll paste the DOM here and then try manually downgrading and upgrading stepwise as suggested by @AlexFromChaos.

**Comment by mattlaw** [comment]
Here we go, Outer HTML of the document element:

[gesturefy.html.txt](https://github.com/Robbendebiene/Gesturefy/files/2307614/gesturefy.html.txt)

**Comment by mattlaw** [comment]
.. and gradual upgrade seems to have done the trick.

**Comment by anatoli26** [comment]
I have 2 profiles under different OS users, in one the extension works at v2.0.2, in another doesn't. Here are printscreens with DevTools open in each profile (the first ps is for the non-working profile):

![not-working](https://user-images.githubusercontent.com/22968420/44431002-04d6f180-a58c-11e8-855b-ec3adb91b0af.png)

========================================

![working](https://user-images.githubusercontent.com/22968420/44431015-13bda400-a58c-11e8-893a-3a9952fad49e.png)

As you can see, DevTools shows different content for the same page, though the actual source-code HTML is the same.

Another observation: the 2.0.2 in the working profile refuses to load (restore) settings saved (backed up) from the 1.2.2 in the profile where 2.0.2 is not working.

Another observation: the 2.0.2 version in the working profile has issues with gestures (i guess due to resistfingerprinting, it takes the start of the gesture at the top left corner), but the 1.2.2 version in the same profile works fine.

**Comment by ashipkowski** [comment]
My wife who runs with gestures and, possibly of note, doesn't tend to restart her browser very often, ran into the same issue (settings screen, no gesture functionality) with 2.0.2 on Windows 10 64-bit, and it was indeed fixed by backtracking to 1.2.2, then upgrading to 2.0.0, and finally to 2.0.2.

**Comment by anatoli26** [comment]
In my case, upgrading from 1.2.2 to 2.0.0 doesn't solve the problem. I upgrade it going to the extension's page -> Version History - See all versions -> Version 2.0.0 [Add to Firefox]. @ashipkowski, have you upgraded it the same way?

**Comment by ashipkowski** [comment]
@anatoli26 I did:
(extension was at 2.0.2)
extension's page -> Version History -> See all versions -> Version 1.2.2 [Add to Firefox]
checked that gestures started working, then
extension's page -> Version History -> See all versions -> Version 2.0.0 [Add to Firefox]
rechecked that gestures were still working
extension's page -> update to 2.0.2

**Comment by Robbendebiene** [comment]
Sorry for the late reply. I had no internet in the last few weeks.

It would be good to know if the console outputs any errors. Maybe some one can post a snapshot of the console here when visiting the addon options page.
To do so:
1. press ctrl + shift + j 
2. press the clear button in the upper left corner
3. (keep the console open) and open Gesturefy's settings page
4. revert to the console and paste the log here

It would also be interesting if someone who has this problem is using Firefox sync.

Sorry for the inconvenience.

**Comment by anatoli26** [comment]
The only log entries I see in the console are what appears in the image below. The "TypeError" entry appears only when clicking on the 3 circles below the menu. The CSS entry about "appearance" also appears in the v1.2.2 so I guess it's unrelated.

Nothing is added to the console if I click on the menu items.

![gest2](https://user-images.githubusercontent.com/22968420/44632311-cfede480-a967-11e8-8c25-3f418c97b2a3.png)

**Comment by Robbendebiene** [comment]
@anatoli26 Thanks for your log. For further debugging I would have to send you a modified version of Gesturefy.

Does anyone have already tried uninstalling Gesturefy, restarting Firefox and reinstalling the latest version? If this is not working than it should at least work on a clean profile, but I understand that this is not a desired solution.

**Comment by anatoli26** [comment]
> For further debugging I would have to send you a modified version of Gesturefy.

Sure, no problem

> Does anyone have already tried uninstalling Gesturefy, restarting Firefox and reinstalling the latest version?

Yes, and it's not working

**Comment by Robbendebiene** [comment]
Sorry for the late reply, I some how lost track of the issue. Does the problem still persist?

**Comment by ashipkowski** [comment]
My wife's setup had the problem recur on the 2.0.3 update; backing down to 1.2.2 and then installing 2.0.0 etc. did not work that time, but uninstalling 2.0.3, shutting down Firefox, removing any obvious Gesturfy-related files from the Firefox profile directory (I checked the plugin ID so this might've been a bit advanced), and then reinstalling 2.0.3 worked. She had no custom configuration so that was easily done.

**Comment by anatoli26** [comment]
In my case, I've tried to do the same as @ashipkowski, but 2.0.2/3 doesn't work in my profile no matter what.

**Comment by Robbendebiene** [comment]
This doesn't matter, unless the provided test add-on is working you can stay with version 1.2.2. My guess is that some of your settings in about:config are misconfigured.

**Comment by anatoli26** [comment]
> 5. you should now see two instances of Gesturefy under about:addons. Open the options page of the new Gesturefy instance (the one that is not disabled)

Only seen 1 instance. Everything else was as you described.


![console1](https://user-images.githubusercontent.com/22968420/45383189-04190480-b5fa-11e8-8f99-6795e91b50c5.png)

![console2](https://user-images.githubusercontent.com/22968420/45383203-0e3b0300-b5fa-11e8-8b7a-270513431cee.png)

**Comment by anatoli26** [comment]
> Did the options page look like the first screenshot of this issue when you tried it?

Yes, the settings screen was exactly as before.

> Btw does the error also occur on a clean Firefox profile?

Haven't tried it in a clean profile, but in another (non-clean) profile 2.0.2 worked after some tweaking...

**Comment by anatoli26** [comment]
> According to the scrollbar you showed me the "oldest" errors and not the most recent ones, but I guess the whole console is spammed with the same error I can see in the screenshot.

Yes, the printscreens contain the only errors that were shown while following your steps. The other errors appeared when another page was updated.

> In this case I'm not able to help you.

Any other way to debug it? Maybe different versions like the test.zip that incorporate partial changes between 1.2.2 and 2.0.0 that could have broken the setup so we can find the offending change?

**Comment by Robbendebiene** [comment]
> Any other way to debug it? Maybe different versions like the test.zip that incorporate partial changes between 1.2.2 and 2.0.0 that could have broken the setup so we can find the offending change?

I'm pretty sure that the problem is caused by Firefox sync (even if you are not using it), because Gesturefy is unable to retrieve the config in your browser and I did not use this API before version 2.0.

What surprises me is that your console outputs did not show a single output I've added in the test.zip. Are you sure that you've visited the Gesturefy options page before you took a snapshot of the console outputs?

The easiest solution probably for you is to create a new clean profile and migrate your add-ons, settings, etc. one by one, even though this might not sound like a proper solution.

**Comment by Robbendebiene** [comment]
If you enable the gesture trail in 1.2.2 you will see that it's not working properly, even though the functionality is not effected. In version 2 I changed this to fix a rare issue that appears on zoomed websites.
So I'm sorry to say that, but I wont revert this. There might be a chance to change this again when the new Firefox overlay API is out, but currently it's unclear when this API will be released and how it will work.

**Comment by Robbendebiene** [comment]
**Short answer**: No

**Long answer:**
I did not want to address this point but since you are repeating it over and over again I'm now telling you my thoughts about this. I was using anti fingerprinting add-ons a long time before Firefox adapted the tor browser settings. In fact this was even my first motivation to write a new Firefox add-on for Firefox 57 and I almost finished it, but stopped because of Mozilla providing a similar functionality. The most important thing I've learned is that anti-fingerprinting techniques can make you more unique. I don't want to raise a discussion here, I do care more about privacy than you might think. All I want to say is, that the provided functionality will not perfectly protect your privacy nor is it the most important thing to protect your internet privacy (it's not bad for sure). I guess you have only 2 options if you still want to use Gesturefy:
1) Use Gesturefy 1.2.2
2) Use add-ons that provide the same or similar functionality as resistfingerprinting does, but give you more control about what methods you want to use against fingerprinting

As I said, this may change in the future, either because Firefox fixes the bug or because of a new API.
