### ISSUE TITLE
Completely broken when using a Wacom stylus

### ISSUE THREAD

**Issue by 3dc1d3** [Robbendebiene/Gesturefy#575]
### Describe your matter in detail
I use a Wacom Intuos Small tablet and after a long time of putting up with terrible hit rates found the issue - Gesturefy receives noisy pen data.

Re-drawing the gestures doesn't help either, in fact it makes it worse as it records the noise which cannot later be reproduced in the same sequence.

The issue is best explained and demonstrated in the following gifs.

Of course the issue is not the Wacom which is famous for not having zigzags in your pen strokes.  But I double checked this by drawing straight lines and circles and don't see any jaggies.

I particular it seems to pick up completely opposite movements in clean strokes jumping erratically with 180 degree turns.

I've tried changing the Algorithm and Sensitivity values, doesn't help much if at all.

Does anyone else use a stylus?  Maybe it is my pen, or maybe it's the way FF handles stylus data.

Also, quite often the input window stops receiving gestures, then glitches out below the input panel - see last gif (I'm not sure if it's related to the pen though...).

Using a mouse is flawless.

### Screenshots or further assistance
v2.1.6 shows the noisy data best:
![v2 1 6](https://user-images.githubusercontent.com/8690075/110592043-e5e1ee80-81cd-11eb-9ba9-cfd0234de8d3.gif)

v3.1.1 shows it in the preview panel:
![v3 1 1](https://user-images.githubusercontent.com/8690075/110592055-e8444880-81cd-11eb-9cf4-93b5e9dfbdfe.gif)

input panel glitch:
![panel-no-response](https://user-images.githubusercontent.com/8690075/110593644-f2674680-81cf-11eb-8e46-ba990dcae964.gif)

### Your System
- Operating system: Win10 18362
- Firefox version: 86.0 64bit Windows (**fresh clean empty profile**)
- Gesturefy version: tested v2.1.6 and v3.1.1

**Comment by Robbendebiene** [comment]
A very laudable issue report!

Since I cannot test the issue myself this will need some further investigation by you.

I wrote a little script which logs every pointer position: https://codepen.io/Robbendebiene/pen/qBqLEKv
Maybe you can use this with your pen and draw some straight lines. After that check if you can see any strange outputs and post them here. Note the script will only log if the left mouse button is pressed. If you cannot do this with your pen you need to change the number in this line of code `if (event.buttons !== 1) return;` to 2 in order to use the right mouse button.

At the moment I don't really have a clue what could cause the issue other then false data provided either by Firefox or your pen.

**Comment by 3dc1d3** [comment]
Thanks for the kind words and the script!  Here goes...


Observations:
- Definitely the data jumps backwards in both axes
- Mouse also seems to jump around a bit - very weird, weirder still that it somehow doesn't affect Gesturefy
- The pen strokes have a final `pointerdown` + `mousemove` events when I click the 'Stop' button, probably due to being more sensitive to hand quiver/tilt etc.
- There's no `pointerup` event for either device...???


<details>
  <summary>
Pen diagonal stroke:
  </summary>
  
```
pointerdown x: 202 y: 84
mousemove x: 201 y: 84
mousemove x: 201 y: 85
mousemove x: 201 y: 86
mousemove x: 204 y: 88
mousemove x: 202 y: 87
mousemove x: 207 y: 89
mousemove x: 210 y: 92
mousemove x: 214 y: 95
mousemove x: 223 y: 102
mousemove x: 219 y: 98
mousemove x: 231 y: 109
mousemove x: 227 y: 105
mousemove x: 240 y: 120
mousemove x: 238 y: 117
mousemove x: 235 y: 113
mousemove x: 246 y: 127
mousemove x: 243 y: 124
mousemove x: 249 y: 130
mousemove x: 251 y: 133
mousemove x: 255 y: 136
mousemove x: 258 y: 139
mousemove x: 264 y: 144
mousemove x: 261 y: 141
mousemove x: 271 y: 148
mousemove x: 274 y: 150
mousemove x: 279 y: 154
mousemove x: 277 y: 152
mousemove x: 284 y: 159
mousemove x: 282 y: 157
mousemove x: 287 y: 161
mousemove x: 289 y: 163
mousemove x: 291 y: 165
mousemove x: 295 y: 169
mousemove x: 293 y: 167
mousemove x: 297 y: 171
mousemove x: 299 y: 173
mousemove x: 305 y: 177
mousemove x: 302 y: 175
mousemove x: 310 y: 181
mousemove x: 307 y: 179
mousemove x: 315 y: 185
mousemove x: 312 y: 183
mousemove x: 318 y: 188
mousemove x: 324 y: 194
mousemove x: 321 y: 191
mousemove x: 331 y: 200
mousemove x: 327 y: 197
mousemove x: 335 y: 203
mousemove x: 338 y: 207
mousemove x: 346 y: 213
mousemove x: 342 y: 210
mousemove x: 354 y: 219
mousemove x: 350 y: 216
mousemove x: 358 y: 222
mousemove x: 365 y: 228
mousemove x: 361 y: 225
mousemove x: 371 y: 233
mousemove x: 368 y: 230
mousemove x: 374 y: 236
mousemove x: 378 y: 239
mousemove x: 381 y: 242
mousemove x: 385 y: 245
mousemove x: 394 y: 252
mousemove x: 389 y: 249
mousemove x: 398 y: 255
mousemove x: 402 y: 259
mousemove x: 406 y: 262
mousemove x: 413 y: 268
mousemove x: 409 y: 265
mousemove x: 419 y: 273
mousemove x: 416 y: 270
mousemove x: 422 y: 275
mousemove x: 428 y: 279
mousemove x: 425 y: 277
mousemove x: 435 y: 283
mousemove x: 431 y: 281
mousemove x: 438 y: 285
mousemove x: 441 y: 288
mousemove x: 445 y: 290
mousemove x: 448 y: 292
mousemove x: 454 y: 296
mousemove x: 451 y: 294
mousemove x: 462 y: 302
mousemove x: 459 y: 300
mousemove x: 457 y: 298
mousemove x: 467 y: 306
mousemove x: 465 y: 304
mousemove x: 472 y: 309
mousemove x: 469 y: 308
mousemove x: 474 y: 311
mousemove x: 476 y: 313
mousemove x: 480 y: 316
mousemove x: 478 y: 314
mousemove x: 482 y: 317
mousemove x: 484 y: 318
mousemove x: 486 y: 319
mousemove x: 488 y: 320
mousemove x: 489 y: 321
mousemove x: 492 y: 323
mousemove x: 490 y: 322
mousemove x: 493 y: 324
mousemove x: 494 y: 325
mousemove x: 496 y: 326
mousemove x: 495 y: 326
mousemove x: 497 y: 327
mousemove x: 496 y: 327
mousemove x: 498 y: 327
mousemove x: 498 y: 328
mousemove x: 499 y: 329
mousemove x: 499 y: 330
mousemove x: 499 y: 332
mousemove x: 499 y: 331
pointerdown x: 86 y: 20
mousemove x: 86 y: 18
mousemove x: 85 y: 18 
```

</details>

<details>
  <summary>
Mouse diagonal:
  </summary>

```
pointerdown x: 103 y: 84
mousemove x: 103 y: 83
mousemove x: 103 y: 84
mousemove x: 104 y: 87
mousemove x: 115 y: 102
mousemove x: 109 y: 94
mousemove x: 134 y: 120
mousemove x: 125 y: 111
mousemove x: 154 y: 138
mousemove x: 143 y: 127
mousemove x: 173 y: 156
mousemove x: 164 y: 147
mousemove x: 191 y: 174
mousemove x: 182 y: 165
mousemove x: 215 y: 196
mousemove x: 205 y: 186
mousemove x: 235 y: 213
mousemove x: 227 y: 207
mousemove x: 265 y: 238
mousemove x: 250 y: 226
mousemove x: 287 y: 259
mousemove x: 274 y: 246
mousemove x: 305 y: 276
mousemove x: 296 y: 268
mousemove x: 325 y: 295
mousemove x: 317 y: 288
mousemove x: 352 y: 324
mousemove x: 346 y: 318
mousemove x: 340 y: 310
mousemove x: 332 y: 303
mousemove x: 367 y: 340
mousemove x: 359 y: 331
mousemove x: 385 y: 355
mousemove x: 410 y: 379
mousemove x: 403 y: 372
mousemove x: 394 y: 364
mousemove x: 419 y: 387
mousemove x: 413 y: 382
mousemove x: 427 y: 396
mousemove x: 424 y: 391
mousemove x: 430 y: 399
mousemove x: 427 y: 397
mousemove x: 431 y: 402
mousemove x: 431 y: 400
mousemove x: 434 y: 403
mousemove x: 431 y: 403
mousemove x: 437 y: 406
mousemove x: 436 y: 405
mousemove x: 443 y: 411
mousemove x: 440 y: 408
mousemove x: 448 y: 414
mousemove x: 446 y: 412
mousemove x: 448 y: 415
mousemove x: 451 y: 418
mousemove x: 451 y: 417
mousemove x: 452 y: 418
mousemove x: 460 y: 426
mousemove x: 455 y: 423
mousemove x: 472 y: 435
mousemove x: 467 y: 432
mousemove x: 463 y: 429
mousemove x: 478 y: 438
mousemove x: 476 y: 436
mousemove x: 484 y: 442
mousemove x: 481 y: 441
mousemove x: 487 y: 445
mousemove x: 485 y: 444
mousemove x: 488 y: 445
pointerdown x: 91 y: 23 
```

</details>


<details>
  <summary>
Pen horizontal:
  </summary>

```
pointerdown x: 80 y: 131
mousemove x: 80 y: 132
mousemove x: 81 y: 132
mousemove x: 83 y: 132
mousemove x: 86 y: 132
mousemove x: 84 y: 132
mousemove x: 88 y: 132
mousemove x: 90 y: 132
mousemove x: 92 y: 131
mousemove x: 96 y: 131
mousemove x: 94 y: 131
mousemove x: 101 y: 130
mousemove x: 98 y: 131
mousemove x: 107 y: 129
mousemove x: 105 y: 129
mousemove x: 103 y: 130
mousemove x: 110 y: 128
mousemove x: 108 y: 129
mousemove x: 112 y: 128
mousemove x: 113 y: 128
mousemove x: 115 y: 127
mousemove x: 118 y: 127
mousemove x: 122 y: 126
mousemove x: 120 y: 127
mousemove x: 129 y: 126
mousemove x: 127 y: 126
mousemove x: 133 y: 125
mousemove x: 131 y: 125
mousemove x: 137 y: 124
mousemove x: 135 y: 125
mousemove x: 141 y: 124
mousemove x: 139 y: 124
mousemove x: 144 y: 123
mousemove x: 148 y: 122
mousemove x: 146 y: 123
mousemove x: 151 y: 122
mousemove x: 154 y: 121
mousemove x: 157 y: 120
mousemove x: 159 y: 120
mousemove x: 164 y: 119
mousemove x: 162 y: 119
mousemove x: 172 y: 118
mousemove x: 169 y: 118
mousemove x: 167 y: 118
mousemove x: 177 y: 117
mousemove x: 174 y: 117
mousemove x: 184 y: 115
mousemove x: 181 y: 116
mousemove x: 187 y: 115
mousemove x: 191 y: 114
mousemove x: 194 y: 113
mousemove x: 198 y: 113
mousemove x: 203 y: 112
mousemove x: 210 y: 112
mousemove x: 208 y: 112
mousemove x: 215 y: 112
mousemove x: 212 y: 112
mousemove x: 221 y: 111
mousemove x: 218 y: 112
mousemove x: 224 y: 111
mousemove x: 228 y: 111
mousemove x: 236 y: 109
mousemove x: 241 y: 109
mousemove x: 245 y: 108
mousemove x: 250 y: 107
mousemove x: 260 y: 106
mousemove x: 255 y: 107
mousemove x: 269 y: 105
mousemove x: 264 y: 106
mousemove x: 277 y: 104
mousemove x: 273 y: 105
mousemove x: 288 y: 103
mousemove x: 284 y: 103
mousemove x: 291 y: 102
mousemove x: 295 y: 102
mousemove x: 299 y: 102
mousemove x: 302 y: 101
mousemove x: 310 y: 100
mousemove x: 317 y: 100
mousemove x: 313 y: 100
mousemove x: 328 y: 98
mousemove x: 324 y: 99
mousemove x: 320 y: 99
mousemove x: 336 y: 97
mousemove x: 332 y: 98
mousemove x: 340 y: 97
mousemove x: 344 y: 96
mousemove x: 348 y: 96
mousemove x: 351 y: 96
mousemove x: 358 y: 95
mousemove x: 362 y: 95
mousemove x: 368 y: 94
mousemove x: 365 y: 94
mousemove x: 374 y: 94
mousemove x: 371 y: 94
mousemove x: 384 y: 93
mousemove x: 381 y: 93
mousemove x: 378 y: 94
mousemove x: 392 y: 92
mousemove x: 388 y: 93
mousemove x: 400 y: 91
mousemove x: 396 y: 92
mousemove x: 404 y: 91
mousemove x: 408 y: 91
mousemove x: 416 y: 90
mousemove x: 412 y: 90
mousemove x: 423 y: 90
mousemove x: 432 y: 89
mousemove x: 430 y: 89
mousemove x: 426 y: 89
mousemove x: 438 y: 89
mousemove x: 435 y: 89
mousemove x: 440 y: 89
mousemove x: 443 y: 88
mousemove x: 445 y: 88
mousemove x: 447 y: 88
mousemove x: 451 y: 88
mousemove x: 455 y: 88
mousemove x: 463 y: 88
mousemove x: 460 y: 88
mousemove x: 468 y: 88
mousemove x: 465 y: 88
mousemove x: 472 y: 88
mousemove x: 475 y: 88
mousemove x: 482 y: 88
mousemove x: 490 y: 89
mousemove x: 486 y: 89
mousemove x: 493 y: 89
mousemove x: 497 y: 89
mousemove x: 500 y: 90
mousemove x: 505 y: 90
mousemove x: 503 y: 90
mousemove x: 511 y: 90
mousemove x: 514 y: 91
mousemove x: 520 y: 91
mousemove x: 517 y: 91
mousemove x: 526 y: 91
mousemove x: 523 y: 91
mousemove x: 529 y: 91
mousemove x: 532 y: 91
mousemove x: 537 y: 91
mousemove x: 534 y: 91
mousemove x: 542 y: 91
mousemove x: 548 y: 91
mousemove x: 545 y: 91
mousemove x: 550 y: 91
mousemove x: 556 y: 91
mousemove x: 553 y: 91
mousemove x: 561 y: 91
mousemove x: 559 y: 91
mousemove x: 566 y: 91
mousemove x: 569 y: 92
mousemove x: 571 y: 92
mousemove x: 572 y: 92
mousemove x: 568 y: 92
mousemove x: 570 y: 92
mousemove x: 571 y: 92
pointerdown x: 94 y: 17
mousemove x: 90 y: 20
mousemove x: 90 y: 21
```

</details>


<details>
  <summary>
Mouse horizontal:
  </summary>

```
pointerdown x: 158 y: 135
mousemove x: 160 y: 135
mousemove x: 161 y: 135
mousemove x: 169 y: 135
mousemove x: 166 y: 135
mousemove x: 173 y: 135
mousemove x: 172 y: 135
mousemove x: 176 y: 136
mousemove x: 175 y: 135
mousemove x: 178 y: 136
mousemove x: 182 y: 136
mousemove x: 181 y: 136
mousemove x: 179 y: 136
mousemove x: 184 y: 136
mousemove x: 190 y: 136
mousemove x: 188 y: 136
mousemove x: 185 y: 136
mousemove x: 193 y: 136
mousemove x: 191 y: 136
mousemove x: 196 y: 136
mousemove x: 194 y: 136
mousemove x: 199 y: 135
mousemove x: 196 y: 135
mousemove x: 202 y: 135
mousemove x: 200 y: 135
mousemove x: 205 y: 134
mousemove x: 203 y: 135
mousemove x: 206 y: 134
mousemove x: 208 y: 134
mousemove x: 211 y: 134
mousemove x: 209 y: 134
mousemove x: 218 y: 134
mousemove x: 215 y: 134
mousemove x: 227 y: 134
mousemove x: 223 y: 134
mousemove x: 244 y: 134
mousemove x: 236 y: 134
mousemove x: 230 y: 134
mousemove x: 248 y: 134
mousemove x: 265 y: 134
mousemove x: 260 y: 134
mousemove x: 269 y: 134
mousemove x: 266 y: 134
mousemove x: 275 y: 135
mousemove x: 272 y: 134
mousemove x: 281 y: 135
mousemove x: 278 y: 135
mousemove x: 287 y: 135
mousemove x: 284 y: 135
mousemove x: 296 y: 136
mousemove x: 293 y: 136
mousemove x: 304 y: 136
mousemove x: 301 y: 136
mousemove x: 308 y: 136
mousemove x: 307 y: 136
mousemove x: 314 y: 138
mousemove x: 311 y: 136
mousemove x: 319 y: 138
mousemove x: 316 y: 138
mousemove x: 323 y: 138
mousemove x: 322 y: 138
mousemove x: 329 y: 138
mousemove x: 326 y: 138
mousemove x: 334 y: 138
mousemove x: 331 y: 138
mousemove x: 338 y: 138
mousemove x: 347 y: 138
mousemove x: 343 y: 138
mousemove x: 353 y: 138
mousemove x: 350 y: 138
mousemove x: 359 y: 138
mousemove x: 356 y: 138
mousemove x: 367 y: 138
mousemove x: 362 y: 138
mousemove x: 376 y: 138
mousemove x: 370 y: 138
mousemove x: 385 y: 138
mousemove x: 379 y: 138
mousemove x: 389 y: 138
mousemove x: 386 y: 138
mousemove x: 395 y: 138
mousemove x: 394 y: 138
mousemove x: 404 y: 138
mousemove x: 398 y: 138
mousemove x: 410 y: 139
mousemove x: 407 y: 139
mousemove x: 421 y: 139
mousemove x: 418 y: 139
mousemove x: 430 y: 139
mousemove x: 425 y: 139
mousemove x: 440 y: 141
mousemove x: 437 y: 141
mousemove x: 445 y: 141
mousemove x: 442 y: 141
mousemove x: 448 y: 141
mousemove x: 446 y: 141
mousemove x: 452 y: 141
mousemove x: 449 y: 141
mousemove x: 463 y: 141
mousemove x: 457 y: 141
mousemove x: 473 y: 141
mousemove x: 467 y: 141
mousemove x: 481 y: 141
mousemove x: 476 y: 141
mousemove x: 487 y: 141
mousemove x: 484 y: 141
mousemove x: 493 y: 141
mousemove x: 491 y: 141
mousemove x: 500 y: 141
mousemove x: 496 y: 141
mousemove x: 506 y: 140
mousemove x: 503 y: 140
mousemove x: 515 y: 140
mousemove x: 511 y: 140
mousemove x: 523 y: 140
mousemove x: 520 y: 140
mousemove x: 533 y: 140
mousemove x: 529 y: 140
mousemove x: 542 y: 140
mousemove x: 547 y: 138
mousemove x: 544 y: 140
mousemove x: 554 y: 138
mousemove x: 550 y: 138
mousemove x: 565 y: 138
mousemove x: 560 y: 138
mousemove x: 557 y: 138
mousemove x: 572 y: 137
mousemove x: 569 y: 138
mousemove x: 583 y: 137
mousemove x: 578 y: 137
mousemove x: 592 y: 137
mousemove x: 586 y: 137
mousemove x: 599 y: 137
mousemove x: 595 y: 137
mousemove x: 604 y: 137
mousemove x: 602 y: 137
mousemove x: 610 y: 137
mousemove x: 608 y: 137
mousemove x: 613 y: 137
mousemove x: 611 y: 137
mousemove x: 616 y: 137
mousemove x: 614 y: 137
mousemove x: 620 y: 137
mousemove x: 617 y: 137
mousemove x: 623 y: 137
mousemove x: 622 y: 137
mousemove x: 628 y: 137
mousemove x: 626 y: 137
mousemove x: 634 y: 137
mousemove x: 631 y: 137
mousemove x: 638 y: 137
mousemove x: 637 y: 137
mousemove x: 644 y: 137
mousemove x: 643 y: 137
mousemove x: 641 y: 137
mousemove x: 646 y: 137
mousemove x: 649 y: 137
pointerdown x: 85 y: 23 
```

</details>

**Comment by Robbendebiene** [comment]
> Mouse also seems to jump around a bit - very weird, weirder still that it somehow doesn't affect Gesturefy

I'm sorry, I just realized I made a mistake in my script which results in a wrong order of the logged events. It should work now properly.

> The pen strokes have a final pointerdown + mousemove events when I click the 'Stop' button, probably due to being more sensitive to hand quiver/tilt etc.

Yes, I think we can ignore them.

> There's no pointerup event for either device...???

For completeness I adjusted the code so it should be logged now.

**Comment by 3dc1d3** [comment]
Yep, now the mouse is fine but the pen jumps around:
<details><summary>Pen horizontal:</summary>

  ```
  pointerdown x: 130 y: 158
  mousemove x: 140 y: 158
  mousemove x: 145 y: 157
  mousemove x: 164 y: 156
  mousemove x: 153 y: 157
  mousemove x: 177 y: 155
  mousemove x: 191 y: 154
  mousemove x: 205 y: 152
  mousemove x: 218 y: 151
  mousemove x: 246 y: 148
  mousemove x: 231 y: 150
  mousemove x: 295 y: 143
  mousemove x: 278 y: 145
  mousemove x: 261 y: 147
  mousemove x: 331 y: 138
  mousemove x: 313 y: 141
  mousemove x: 368 y: 134
  mousemove x: 349 y: 136
  mousemove x: 386 y: 131
  mousemove x: 404 y: 129
  mousemove x: 439 y: 126
  mousemove x: 422 y: 127
  mousemove x: 455 y: 125
  mousemove x: 470 y: 125
  mousemove x: 485 y: 124
  mousemove x: 511 y: 123
  mousemove x: 498 y: 123
  mousemove x: 532 y: 121
  mousemove x: 522 y: 122
  mousemove x: 559 y: 118
  mousemove x: 551 y: 119
  mousemove x: 542 y: 120
  mousemove x: 573 y: 116
  mousemove x: 567 y: 117
  mousemove x: 578 y: 115
  mousemove x: 582 y: 115
  mousemove x: 585 y: 115
  mousemove x: 589 y: 114
  mousemove x: 598 y: 113
  mousemove x: 593 y: 114
  mousemove x: 606 y: 112
  mousemove x: 602 y: 113
  mousemove x: 615 y: 110
  mousemove x: 612 y: 111
  mousemove x: 609 y: 111
  mousemove x: 619 y: 109
  mousemove x: 618 y: 109
  mousemove x: 621 y: 109
  mousemove x: 622 y: 108
  mousemove x: 623 y: 108
  mousemove x: 624 y: 108
  mousemove x: 623 y: 108
  mousemove x: 622 y: 108
  pointerup x: 622 y: 108
  pointerdown x: 92 y: 20
  mousemove x: 92 y: 21
  pointerup x: 92 y: 21 
  ```

</details>

  
<details><summary>Mouse horizontal:</summary>

  ```
  pointerdown x: 107 y: 176
  mousemove x: 108 y: 176
  mousemove x: 123 y: 180
  mousemove x: 145 y: 183
  mousemove x: 174 y: 187
  mousemove x: 207 y: 192
  mousemove x: 253 y: 198
  mousemove x: 294 y: 204
  mousemove x: 349 y: 211
  mousemove x: 406 y: 219
  mousemove x: 465 y: 228
  mousemove x: 525 y: 235
  mousemove x: 588 y: 244
  mousemove x: 646 y: 252
  mousemove x: 715 y: 261
  mousemove x: 783 y: 267
  mousemove x: 837 y: 270
  mousemove x: 903 y: 274
  mousemove x: 964 y: 279
  mousemove x: 1018 y: 282
  mousemove x: 1071 y: 285
  mousemove x: 1110 y: 286
  mousemove x: 1162 y: 291
  mousemove x: 1198 y: 294
  mousemove x: 1269 y: 301
  mousemove x: 1297 y: 304
  mousemove x: 1320 y: 309
  mousemove x: 1336 y: 310
  mousemove x: 1342 y: 310
  mousemove x: 1345 y: 312
  pointerup x: 1345 y: 312
  pointerdown x: 77 y: 18
  pointerup x: 77 y: 18
  ```

</details>

  So I tested this in another app and it's the same.  Below is a 'diff' of X positions over time for a horizontal stroke - they should all be positive as X increases but some are clearly negative.
  
  ![image](https://user-images.githubusercontent.com/8690075/110771100-3b8dc800-82ae-11eb-9ad8-b701741c5214.png)
  
  So it's not Gesturefy's fault, but is there something we can do?  Maybe a time-based window would work best?  I doubt anyone's hand can make (or would intentionally make) such drastic changes in direction within milliseconds.
  
  The above graph was captured at roughly 10ms between data points.  So I think a window of 20 should suffice without impacting mouse people.
 
My guess is the pen is picking up on micro changes in pressure and angle which affect where the tip registers most in the tablet grid - and in drawing apps you just don't see it as it paints over the same pixels (unless of course mine is misbehaving...).
  
<details><summary>Here's the data:</summary>
  
  ```
  1028
  1028
  1028
  1028
  1027
  1027
  1026
  1026
  1026
  1025
  1025
  1025
  1024
  1024
  1024
  1023
  1023
  1023
  1022
  1022
  1021
  1021
  1021
  1020
  1020
  1020
  1020
  1020
  1020
  1019
  1019
  1019
  1019
  1019
  1019
  1019
  1019
  1019
  1019
  1019
  1019
  1019
  1020
  1020
  1020
  1020
  1020
  1020
  1020
  1020
  1020
  1020
  1021
  1021
  1022
  1022
  1023
  1023
  1024
  1024
  1025
  1025
  1026
  1026
  1026
  1027
  1027
  1027
  1027
  1028
  1028
  1029
  1029
  1030
  1030
  1030
  1030
  1031
  1031
  1031
  1032
  1032
  1033
  1033
  1034
  1034
  1035
  1036
  1036
  1037
  1038
  1038
  1039
  1040
  1040
  1041
  1042
  1043
  1044
  1046
  1047
  1048
  1049
  1050
  1050
  1051
  1052
  1053
  1054
  1055
  1055
  1056
  1057
  1057
  1058
  1058
  1059
  1059
  1060
  1062
  1064
  1068
  1073
  1079
  1086
  1091
  1096
  1100
  1103
  1107
  1110
  1113
  1117
  1120
  1124
  1128
  1132
  1135
  1139
  1142
  1146
  1149
  1152
  1155
  1158
  1160
  1163
  1165
  1168
  1170
  1172
  1175
  1177
  1180
  1182
  1184
  1187
  1189
  1190
  1191
  1192
  1193
  1194
  1195
  1197
  1200
  1202
  1204
  1204
  1205
  1206
  1206
  1207
  1207
  1207
  1208
  1208
  1209
  1210
  1212
  1214
  1215
  1217
  1219
  1222
  1224
  1227
  1230
  1233
  1238
  1245
  1255
  1268
  1282
  1296
  1307
  1317
  1326
  1334
  1343
  1352
  1362
  1372
  1383
  1394
  1404
  1415
  1425
  1436
  1446
  1457
  1467
  1477
  1488
  1498
  1508
  1518
  1528
  1537
  1547
  1557
  1567
  1577
  1587
  1597
  1607
  1616
  1625
  1634
  1643
  1653
  1662
  1671
  1680
  1689
  1698
  1706
  1714
  1722
  1730
  1737
  1745
  1752
  1759
  1766
  1773
  1779
  1784
  1788
  1791
  1794
  1799
  1803
  1808
  1813
  1817
  1822
  1825
  1829
  1832
  1835
  1839
  1842
  1846
  1849
  1853
  1856
  1858
  1860
  1861
  1861
  1862
  1862
  1862
  1862
  1861
  1861
  1860
  1859
  1859
  1858
  1857
  1857
  1856
  1856
  1856
  1855
  1855
  1855
  1855
  1855
  1855
  1855
  1855
  1855
  1855
  1855
  1855
  1854
  1854
  1854
  1854
  1854
  1854
  1854
  1854
  1854
  1854
  1854
  1854
  1854
  1854
  1854
  1854
  1854
  1854
  1854
  1854
  1854
  1854
  1854
  1854
  1854
  1854
  1853
  1853
  1853
  1853
  1853
  1853
  1853
  1853
  1853
  1853
  1853
  1853
  1853
  1853
  1853
  1853
  1853
  1853
  1853
  1853
  1853
  1853
  1853
  1853
  1853
  ```

</details>

**Comment by Robbendebiene** [comment]
>  Maybe a time-based window would work best? I doubt anyone's hand can make (or would intentionally make) such drastic changes in direction within milliseconds.

I agree but it should be properly tested so it doesn't break any existing functionality.

I wonder if this could also be prevented by taking some of the other properties into account that are listed here: https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events#pointerevent_interface However I have no experience in using a stylus so I can only speculate.

Gesturefy version 2 provided an advanced setting to change the minimal mouse movement until a new point is registered. Maybe bringing back this setting could also solve your problem? At the moment it is set to 10 pixel (fixed) but something like 30 might already be enough to circumvent the problem.

**Comment by 3dc1d3** [comment]
I could play around with that setting in v2 but since it's fixed, and I don't know the process for building and testing locally, I don't know how to test it.  Can I change that variable at runtime in the addon debugger?

**Comment by Robbendebiene** [comment]
I would suggest you download the [latest version](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.1.1) and edit the second parameter in [line 1975](https://github.com/Robbendebiene/Gesturefy/blob/master/src/core/workarounds/content.bundle.js#L1975) in the "/src/core/workarounds/content.bundle.js" file.

To load the extension go to `about:debugging#/runtime/this-firefox`, click "load temporary add-on" and select the manifest.json. This will overwrite the current Gesturefy installation for this browser session. After a restart everything will be back to normal.
Every time you change the distance threshold value you should click the add-on "reload button" in `about:debugging#/runtime/this-firefox`

**Comment by 3dc1d3** [comment]
Awesome!  Thank you.

**Comment by 3dc1d3** [comment]
That's made a huge improvement!  But it looks like that change isn't being picked up by the gesture recorder panel which still glitches a lot and basically makes any recorded gestures unusable.

Likewise the drawing of the gesture trail on a regular page also shows jaggies so I'd say they're related.

**Comment by Robbendebiene** [comment]
>  But it looks like that change isn't being picked up by the gesture recorder panel which still glitches a lot and basically makes any recorded gestures unusable.

This is true. You would have to change [this line](https://github.com/Robbendebiene/Gesturefy/blob/master/src/views/options/js/content/gestures.js#L687) as well.

> Likewise the drawing of the gesture trail on a regular page also shows jaggies so I'd say they're related. 

This also makes sense, because since version 3.0 the gesture trail is decoupled from the detection logic.

It would be interesting if you notice any drawbacks of setting the distance threshold to a higher value. You can see the basic functionality of the pattern extractor here: https://codepen.io/Robbendebiene/pen/LYVBQmy (make sure to choose one of the first 2 algorithms) Here you can also change the global variable in the right code panel at the top. If you choose a value like 100 you will notice that some fine mouse movements won't be detected anymore.

![grafik](https://user-images.githubusercontent.com/13716661/111440132-545f0900-8706-11eb-9f4b-72ed359f59b2.png)


This could be improved by always accumulating the distance instead of only checking if the distance from the last registered point to the current point exceeds some value. However this setting was made to ignore/filter tiny movements completely, which wouldn't be the case anymore.

**Comment by 3dc1d3** [comment]
Thank you for providing these codepens!

Here are my results... not really sure but doesn't look great overall.

Algo1 at threshold 5 seems to have the least noise but also causes problems with registering correct gestures.

![sshot-001](https://user-images.githubusercontent.com/8690075/111577799-14337f80-8807-11eb-882e-6793db7006cb.jpg)
![sshot-002](https://user-images.githubusercontent.com/8690075/111577800-14337f80-8807-11eb-88db-9129c46f0cf3.jpg)
![sshot-003](https://user-images.githubusercontent.com/8690075/111577804-14cc1600-8807-11eb-8df2-87f802c7ab4b.jpg)
![sshot-004](https://user-images.githubusercontent.com/8690075/111577776-0ed63500-8807-11eb-8ab8-f4827ecf6aef.jpg)
![sshot-005](https://user-images.githubusercontent.com/8690075/111577779-10076200-8807-11eb-9972-71e94fc04082.jpg)
![sshot-006](https://user-images.githubusercontent.com/8690075/111577781-109ff880-8807-11eb-8934-87abd23f3500.jpg)
![sshot-007](https://user-images.githubusercontent.com/8690075/111577782-109ff880-8807-11eb-906c-d9ae13b381d8.jpg)
![sshot-013](https://user-images.githubusercontent.com/8690075/111578276-f286c800-8807-11eb-925d-8f612c74576f.jpg)
![sshot-014](https://user-images.githubusercontent.com/8690075/111578360-1c3fef00-8808-11eb-8299-8674aa7671b6.jpg)

![sshot-008](https://user-images.githubusercontent.com/8690075/111577783-11388f00-8807-11eb-8560-8a42a93291fa.jpg)
![sshot-009](https://user-images.githubusercontent.com/8690075/111577787-1269bc00-8807-11eb-8a5c-695f918dea8f.jpg)
![sshot-010](https://user-images.githubusercontent.com/8690075/111577790-1269bc00-8807-11eb-9903-56273b02af59.jpg)
![sshot-011](https://user-images.githubusercontent.com/8690075/111577794-13025280-8807-11eb-918e-a15ba870975f.jpg)
![sshot-012](https://user-images.githubusercontent.com/8690075/111577797-139ae900-8807-11eb-9fae-03bbb8321e14.jpg)

**Comment by Robbendebiene** [comment]
Sorry for the misunderstanding. What you actually changed is the direction threshold and not the distance threshold. (I made this pen a while a go to test the different algorithms so for this case it probably was a bit confusing).

> Here you can also change the global variable in the right code panel at the top.

What I meant by this is that you have to change a variable in the actual code which was right at the top of the code. I've updated the panel so it includes a second input which changes the distance threshold. This is the only thing that should interest you at the moment :)

At the end this just visualizes of how the pattern detection algorithm works but tells us little how a higher value in the distance threshold effects the gesture recognition on a daily basis. However it might be a good way to discover the minimal value that is required to filter the noisy pen data.

**Comment by 3dc1d3** [comment]
31 is absolute minimum but 36 is about 80% of the way, but still results in thing like this:
![Screenshot_2021-03-25 LYVBQmy](https://user-images.githubusercontent.com/8690075/112406495-637a3280-8d68-11eb-8c0e-5eb25843c1be.png)

That doesn't even make sense to me, and doesn't look like minor noise around a fixed point.  very strange.

at 60 there were just occasional odd jumps.

Mouse doesn't seem to be affected at 36 or even 60.

Is it possible to release an update that exposes this variable in the UI?

**Comment by Robbendebiene** [comment]
I've released a new version which should be available soon. It will provide 2 new hidden settings.
You can only activate/change them by manually editing the config file. To do so I suggest backing up your config, editing it and then reimporting it.
The relevant setting is called `patternDistanceThreshold` and should be placed in the json file as shown below.

```
Settings: {
  Gesture: {
    patternDistanceThreshold: 50
  }
}
```

**Comment by 3dc1d3** [comment]
Hi @Robbendebiene sorry for late response, just tried it and seems to work perfectly - thank you very much!

However, that glitch still happens when drawing new gestures (where a second ghost gesture appears below and outside the input area and no longer responds to input) - I have to re-open the Gesturefy config page.

**Comment by Robbendebiene** [comment]
@3dc1d3 Thanks for your update. I'm glad this setting helps you to work around your problem.

> However, that glitch still happens when drawing new gestures (where a second ghost gesture appears below and outside the input area and no longer responds to input) - I have to re-open the Gesturefy config page.

Does this only happen when you draw the gesture with your pen or can you also reproduce the bug with your mouse? Would you mind opening a new issue for this with a recording that shows how the error occurs?

**Comment by 3dc1d3** [comment]
seems to be with the pen only.  a gif is attached above as 'input panel glitch' but I'll make a new ticket.
